var index = 6;
function insertRow(){
            var table=document.getElementById("myTable");
            var row=table.insertRow(table.rows.length);
            var cell1=row.insertCell(0);
                cell1.class = "column1";
            var t1=document.createElement("input");
            	t1.type = "text";
                t1.name = index++ + "";
                t1.placeholder = "Chemical Name";
                cell1.appendChild(t1);
            var cell2=row.insertCell(1);
            var t2=document.createElement("input");
                t2.type = "text";
                t2.name = index++ + "";
                t2.placeholder = "CAS number";
                cell2.appendChild(t2);
            var cell3=row.insertCell(2);
            var t3=document.createElement("input");
                t3.type = "text";
                t3.name = index++ + "";
                t3.placeholder = "PUB CHEM Number";
                cell3.appendChild(t3);
            var cell4=row.insertCell(3);
            var t4=document.createElement("input");
                t4.type = "text";
                t4.name = index++ + "";
                t4.placeholder = "Molecular Weight";
                cell4.appendChild(t4);
            var cell5=row.insertCell(4);
            var t5=document.createElement("input");
                t5.type = "text";
                t5.name = index++ + "";
                t5.placeholder = "Density";
                cell5.appendChild(t5);
}
function insertRow1(){
            var table=document.getElementById("myTable1");
            var row=table.insertRow(table.rows.length);
            var cell1=row.insertCell(0);
            var t1=document.createElement("input");
            	t1.type = "text";
                t1.name = index++ + "";
                t1.placeholder = "CAS RN";
                cell1.appendChild(t1);
            var cell2=row.insertCell(1);
            var t2=document.createElement("input");
                t2.type = "text";
                t2.name = index++ + "";
                t2.placeholder = "Purity";
                cell2.appendChild(t2);
            var cell3=row.insertCell(2);
            var t3=document.createElement("input");
                t3.type = "text";
                t3.name = index++ + "";
                t3.placeholder = "Nature";
                cell3.appendChild(t3);
            var cell4=row.insertCell(3);
            var t4=document.createElement("input");
                t4.type = "text";
                t4.name = index++ + "";
                t4.placeholder = "Min Quantity";
                cell4.appendChild(t4);
            var cell5=row.insertCell(4);
            var t5=document.createElement("input");
                t5.type = "text";
                t5.name = index++ + "";
                t5.placeholder = "Max Quantity";
                cell5.appendChild(t5);
}
var index1 = 3;
function insertnewRow(){
            var table=document.getElementById("myTable2");
            var row=table.insertRow(table.rows.length);
            var cell1=row.insertCell(0);
            var t1=document.createElement("input");
                t1.type = "text";
                t1.name = index1++ + "";
                t1.placeholder = "User Name";
                cell1.appendChild(t1);
            var cell2=row.insertCell(1);
            var t2=document.createElement("input");
                t2.type = "text";
                t2.name = index1++ + "";
                t2.placeholder = "Password";
                cell2.appendChild(t2);
}